### ISSUE TITLE
Add organization model

### ISSUE THREAD

**Issue by 2KAbhishek** [incubyte/incuhive#4]
Add the organization model

- Has many panelist
- Name
- Invite Code

Implement features for users to create and join organizations:

Organization Creation:

- Panelist can create a new organization.
- Invite Members
- Update their own org by updating the invite code
- Add a section for updating the organization using the Org ID, performing a DB update to add the user.

**Comment by kartik-madhak** [comment]
- Implemented an organization create form that can be accessed by `/organizations/new`. It displays relevant errors/success message in the same page.
- Implemented view route with ability to edit name and regen invite code. Accessed by `organizations/<id>`

# notes
- Invite panelists is blocked by #3 
- The new organization create and update forms needs to be put behind auth. blocked by #7 
- Invite panelist is blocked by #7 as well

**Comment by 2KAbhishek** [comment]
implemented
